# Generated by Django 3.2.12 on 2022-03-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default=True, max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='photos/organizations')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_church', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationOverview',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organization.organization')),
                ('mandate', models.TextField(blank=True, max_length=500)),
                ('mission_statement', models.TextField(blank=True, max_length=500)),
                ('vision', models.TextField(blank=True, max_length=500)),
                ('philosophy', models.TextField(blank=True, max_length=500)),
                ('population', models.TextField(blank=True, max_length=500)),
                ('branch', models.TextField(blank=True, max_length=500)),
                ('Cell_fellowship', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
