# Generated by Django 3.2.12 on 2022-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationoverview_service_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationoverview',
            name='service_invite',
        ),
        migrations.AddField(
            model_name='organization',
            name='service_invite',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
