# Generated by Django 3.2.12 on 2022-04-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='activity',
        ),
    ]
