# Generated by Django 3.2.12 on 2022-04-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220325_1318'),
        ('gallery', '0003_remove_gallery_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='organization',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
