# Generated by Django 3.2.12 on 2022-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/preachers')),
                ('is_worker', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'preacher',
                'verbose_name_plural': 'preachers',
            },
        ),
    ]
