# Generated by Django 3.2.12 on 2022-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('phone', models.EmailField(blank=True, max_length=100)),
                ('channel', models.CharField(choices=[(0, 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Whatsapp', 'Whatsapp'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Ads', 'Ads'), ('others', 'Others')], default=0, max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
