# Generated by Django 3.2.12 on 2022-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20220404_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='instruction',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
