# Generated by Django 3.2.12 on 2022-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_contactform_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
