# Generated by Django 3.2.12 on 2022-04-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_contactform_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='instruction',
        ),
    ]
