# Generated by Django 3.2.12 on 2022-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20220411_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/activity_type'),
        ),
    ]
