# Generated by Django 3.2.12 on 2022-04-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220325_1318'),
        ('activity', '0004_auto_20220412_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='description',
            new_name='testimony_description',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='image',
            new_name='testimony_image',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='city',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='country',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='organization',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='state',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='testifier_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
